### ISSUE TITLE
Revision string instead of revision number causes ParseException

### ISSUE THREAD

**Issue by gnbl** [xesscorp/kinparse#2]
Attempting to parse a netlist like
```
(export (version D)
  (design
    (source "xxx.sch")
    (date "14/02/2018 11:07:30")
    (tool "Eeschema 4.0.7")
    (sheet (number 1) (name /) (tstamps /)
      (title_block
        (title)
        (company)
        (rev a)
```

fails with a `ParseException` and many "Suppress:" messages that seem not very helpful with debugging (could this output be properly formatted or condensed to point out the actual issue a little more direct?).

Removing data from the failing netlist to more resemble a working one (blank sheet) leads to the culprit: the string "a" string in `rev`, instead of a number as required in: 
https://github.com/xesscorp/kinparse/blob/master/kinparse/kinparse.py#L80

With that info, the error output `				[{Suppress:("(") Suppress:("rev") [{W:(0123...) [{"." [W:(0123...)]}]}] Suppress:(")")}] &` makes a little more sense as it seems to show what is expected (a number).

Replacing this with `rev = _paren_clause('rev', Optional(anystring))` resolves the problem.

**Comment by xesscorp** [comment]
I made the correction you recommended. New version is 0.0.3 and is available on PyPi. Thanks!

As for the clarity of the debugging output, that's pretty much determined by the pyparsing package. I haven't seen any way of tailoring it to make it easier to spot problems.

**Comment by gnbl** [comment]
Great, thank you.

**Comment by Tomaaso** [comment]
Hello, 

I reopen this issue because i have a similary error. There is my .net generated with Kicad6.
Version: 6.0.6-3a73a75311~116~ubuntu20.04.1, release build

[Carte mère.zip](https://github.com/devbisme/kinparse/files/9139207/Carte.mere.zip)

Thanks.

> pyparsing.exceptions.ParseException: Missing one or more required elements ({Suppress:('(') Suppress:('components') [Group:({Suppress:('(') Suppress:('comp') {{Suppress:('(') Suppress:('ref') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')} & {Suppress:('(') Suppress:('value') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')} & [Suppress:('(') Suppress:('datasheet') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')] & [Suppress:('(') Suppress:('fields') [Group:({Suppress:('(') Suppress:('field') {{{Suppress:('(') Suppress:('name') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')} | {Suppress:('(') Suppress:('names') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')}} & [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)]} Suppress:(')')})]... Suppress:(')')] & [Suppress:('(') Suppress:('libsource') {{Suppress:('(') Suppress:('lib') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')} & {Suppress:('(') Suppress:('part') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')} & [Suppress:('(') Suppress:('description') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')]} Suppress:(')')] & [Suppress:('(') Suppress:('footprint') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')] & [Group:({Suppress:('(') Suppress:('sheetpath') {{{Suppress:('(') Suppress:('name') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')} | {Suppress:('(') Suppress:('names') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')}} & {{Suppress:('(') Suppress:('tstamp') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')} | {Suppress:('(') Suppress:('tstamps') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')}}} Suppress:(')')})] & [Suppress:('(') Suppress:('tstamp') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')} | {Suppress:('(') Suppress:('tstamps') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')] & [{Group:({Suppress:('(') Suppress:('property') {{{Suppress:('(') Suppress:('name') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')} | {Suppress:('(') Suppress:('names') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')}} & {Suppress:('(') Suppress:('value') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')}} Suppress:(')')})}...]} Suppress:(')')})]... Suppress:(')')}, {Suppress:('(') Suppress:('nets') [{Suppress:('(') Suppress:('net') Group:({{Suppress:('(') Suppress:('code') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')} & {{Suppress:('(') Suppress:('name') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')} | {Suppress:('(') Suppress:('names') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')}} & Group:({{Suppress:('(') Suppress:('node') Group:({{Suppress:('(') Suppress:('ref') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')} & {Suppress:('(') Suppress:('pin') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')} & [Suppress:('(') Suppress:('pinfunction') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')] & [Suppress:('(') Suppress:('pintype') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SP><TAB><CR><LF>]...) !W:(()) Suppress:([<SP><TAB><CR><LF>]...)] Suppress:(')')]}) Suppress:(')')}}...)}) Suppress:(')')}]... Suppress:(')')}), found '\n'  (at char 21), (line:1, col:22)
