### ISSUE TITLE
long/unclear ParseException

### ISSUE THREAD

**Issue by ErikLambrechts** [xesscorp/kinparse#5]
I try to use `parse_netlist` and get

```
ParseException: Missing one or more required elements ({Suppress:("(") Suppress:("components") [Group:({Suppress:("(") Suppress:("comp") {{Suppress:("(") Suppress:("ref") {{string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SPC><TAB><CR><LF>]...) !W:(()) Suppress:([<SPC><TAB><CR><LF>]...)}} Suppress:(")")} & {Suppress:("(") Suppress:("value") {{string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SPC><TAB><CR><LF>]...) !W:(()) Suppress:([<SPC><TAB><CR><LF>]...)}} Suppress:(")")} & [{Suppress:("(") Suppress:("datasheet") {{string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SPC><TAB><CR><LF>]...) !W:(()) Suppress:([<SPC><TAB><CR><LF>]...)}} Suppress:(")")}] & [{Suppress:("(") Suppress:("fields") [Group:({Suppress:("(") Suppress:("field") {{Suppress:("(") Suppress:("name") {{string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SPC><TAB><CR><LF>]...) !W:(()) Suppress:([<SPC><TAB><CR><LF>]...)}} Suppress:(")")} & {{string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SPC><TAB><CR><LF>]...) !W:(()) Suppress:([<SPC><TAB><CR><LF>]...)}}} Suppress:(")")})]... Suppress:(")")}] & [{Suppress:("(") Suppress:("libsource") {{Suppress:("(") Suppress:("lib") {{string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SPC><TAB><CR><LF>]...) !W:(()) Suppress:([<SPC><TAB><CR><LF>]...)}} Suppress:(")")} &
{Suppress:("(") Suppress:("part") {{string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SPC><TAB><CR><LF>]...) !W:(()) Suppress:([<SPC><TAB><CR><LF>]...)}} Suppress:(")")}} Suppress:(")")}] & [{Suppress:("(") Suppress:("footprint") {{string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SPC><TAB><CR><LF>]...) !W:(()) Suppress:([<SPC><TAB><CR><LF>]...)}} Suppress:(")")}] & [{Suppress:("(") Suppress:("sheetpath") {{Suppress:("(") Suppress:("names") {{string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SPC><TAB><CR><LF>]...) !W:(()) Suppress:([<SPC><TAB><CR><LF>]...)}} Suppress:(")")} & {Suppress:("(") Suppress:("tstamps") {{string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SPC><TAB><CR><LF>]...) !W:(()) Suppress:([<SPC><TAB><CR><LF>]...)}} Suppress:(")")}} Suppress:(")")}] & [{Suppress:("(") Suppress:("tstamp") {{string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SPC><TAB><CR><LF>]...) !W:(()) Suppress:([<SPC><TAB><CR><LF>]...)}} Suppress:(")")}]} Suppress:(")")})]... Suppress:(")")}, {Suppress:("(") Suppress:("nets") [Group:({Suppress:("(") Suppress:("net") {{Suppress:("(") Suppress:("code") W:(0123...) Suppress:(")")} & {Suppress:("(") Suppress:("name") {{string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SPC><TAB><CR><LF>]...) !W:(()) Suppress:([<SPC><TAB><CR><LF>]...)}} Suppress:(")")} & Group:({Group:({Suppress:("(") Suppress:("node") {{Suppress:("(") Suppress:("ref") {{string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SPC><TAB><CR><LF>]...) !W:(()) Suppress:([<SPC><TAB><CR><LF>]...)}} Suppress:(")")} & {Suppress:("(") Suppress:("pin") {{string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([<SPC><TAB><CR><LF>]...) !W:(()) Suppress:([<SPC><TAB><CR><LF>]...)}} Suppress:(")")}} Suppress:(")")})}...)} Suppress:(")")})]... Suppress:(")")}) (at char 19), (line:1, col:20)
```
My first line is 
```
(export (version D)
```
running python 3.6, netlist generated with kicad 5

**Comment by xesscorp** [comment]
Better just send me the netlist file.

**Comment by ErikLambrechts** [comment]
[ref2by2.zip](https://github.com/xesscorp/kinparse/files/2313433/ref2by2.zip)
thanks.

**Comment by xesscorp** [comment]
KiCad V5 started placing part descriptions in the component libsource fields. So now that's handled. Install new version 0.0.4.

**Comment by ErikLambrechts** [comment]
works fine, thanks

**Comment by Tomaaso** [comment]
Hello,

I reopen this issue because i have a similary error. There is my .net generated with Kicad6.
Version: 6.0.6-3a73a75311116ubuntu20.04.1, release build
[Carte mère.zip](https://github.com/devbisme/kinparse/files/9139235/Carte.mere.zip)



Thanks.

>pyparsing.exceptions.ParseException: Missing one or more required elements ({Suppress:('(') Suppress:('components') [Group:({Suppress:('(') Suppress:('comp') {{Suppress:('(') Suppress:('ref') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')} & {Suppress:('(') Suppress:('value') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')} & [Suppress:('(') Suppress:('datasheet') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')] & [Suppress:('(') Suppress:('fields') [Group:({Suppress:('(') Suppress:('field') {{{Suppress:('(') Suppress:('name') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')} | {Suppress:('(') Suppress:('names') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')}} & [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)]} Suppress:(')')})]... Suppress:(')')] & [Suppress:('(') Suppress:('libsource') {{Suppress:('(') Suppress:('lib') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')} & {Suppress:('(') Suppress:('part') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')} & [Suppress:('(') Suppress:('description') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')]} Suppress:(')')] & [Suppress:('(') Suppress:('footprint') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')] & [Group:({Suppress:('(') Suppress:('sheetpath') {{{Suppress:('(') Suppress:('name') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')} | {Suppress:('(') Suppress:('names') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')}} & {{Suppress:('(') Suppress:('tstamp') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')} | {Suppress:('(') Suppress:('tstamps') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')}}} Suppress:(')')})] & [Suppress:('(') Suppress:('tstamp') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')} | {Suppress:('(') Suppress:('tstamps') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')] & [{Group:({Suppress:('(') Suppress:('property') {{{Suppress:('(') Suppress:('name') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')} | {Suppress:('(') Suppress:('names') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')}} & {Suppress:('(') Suppress:('value') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')}} Suppress:(')')})}...]} Suppress:(')')})]... Suppress:(')')}, {Suppress:('(') Suppress:('nets') [{Suppress:('(') Suppress:('net') Group:({{Suppress:('(') Suppress:('code') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')} & {{Suppress:('(') Suppress:('name') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')} | {Suppress:('(') Suppress:('names') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')}} & Group:({{Suppress:('(') Suppress:('node') Group:({{Suppress:('(') Suppress:('ref') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')} & {Suppress:('(') Suppress:('pin') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')} & [Suppress:('(') Suppress:('pinfunction') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')] & [Suppress:('(') Suppress:('pintype') [string enclosed in double quotes ^ string enclosed in single quotes} ^ {Suppress:([]...) !W:(()) Suppress:([]...)] Suppress:(')')]}) Suppress:(')')}}...)}) Suppress:(')')}]... Suppress:(')')}), found '\n' (at char 21), (line:1, col:22)
