### ISSUE TITLE
nlst.design.sheets doesn't return a value

### ISSUE THREAD

**Issue by 4b11b4** [xesscorp/kinparse#7]
These commands all return and using .val returns an error:
nlst.design.tool
nlst.design.date
nlst.design.sheets
nlst.design.source

What does work:
- nlst.design DOES return a lot of information
...scrolling through, it looks like sheet information with some integer value, the string name, the unique timestamp, and 'filename.sch' in some nested dictionary lists

- nlst.components also returns a list

I tested on a 5.0 netlist only.

**Comment by xesscorp** [comment]
This started happening when pyparsing went to their 2.3.0 release. For now, I've restricted kinparse to only use versions of pyparsing < 2.3.0.
